### PR TITLE
Bug: can't depend on a report with parameters

### PR DESCRIPTION
**Pull request by hillalex**
> This PR fixes a number of bugs found by Alex - I've walked back the change to the reports to leave the main error case.
>
> * `current_orderly_parameters` did not actually return the parameters
> * `outpack::outpack_search` needed the parameters argument named - it was being interpreted as name (the error message > now improved in outpack would make this more obvious)
> * the testthat error-swallowing bug now makes this all much more obvious

### CODE REVIEW

**Comment by richfitz** [comment]
This PR fixes a number of bugs found by Alex - I've walked back the change to the reports to leave the main error case.

* `current_orderly_parameters` did not actually return the parameters
* `outpack::outpack_search` needed the parameters argument named - it was being interpreted as `name` (the error message now improved in outpack would make this more obvious)
* the testthat error-swallowing bug now makes this all much more obvious

**Comment by richfitz** [comment]
@hillalex  - I can't add you of course to your own PR!

**Review by hillalex — COMMENTED** [review]
Great, thanks for this!

**Review by r-ash — APPROVED** [review]
Good spot!

**Pull request merged**
